/* ============================================================
   Eissa · Energy and States of Matter
   Original bilingual content written from the lesson concepts
   and the answered Question Bank. No textbook text/art reused.
   ============================================================ */

/* ---------- LESSON (LEARN MODE) ---------- */
const LESSON = [
 { id:'L0', icon:'🔥💧', tagEn:'Phenomenon', tagAr:'الظاهرة',
   tEn:'Why is the liquid boiling?', tAr:'ليش السائل قاعد يغلي؟',
   visual:'boil',
   arBody:'شوف يا عيسى 👀 حطينا ماء على نار. بعد شوي بدأ يطلع فقاعات وبخار.<br>قبل لا نشرح… <b>وش تتوقع يصير للجزيئات لما نسخّن الماء؟</b>',
   enBody:'We put water over a heat source. Soon bubbles appear and steam rises.<br>Before we explain — <b>what do you predict happens to the particles when we heat water?</b>',
   predict:{
     qAr:'اختر توقعك:', qEn:'Choose your prediction:',
     opts:[
       {en:'The particles stop moving.', ar:'الجزيئات تقف عن الحركة.'},
       {en:'The particles move faster and spread apart.', ar:'الجزيئات تتحرك أسرع وتتباعد عن بعض.'},
       {en:'The particles get bigger in size.', ar:'حجم الجزيئات نفسه يكبر.'}
     ], ans:1,
     afterAr:'ممتاز إنك توقعت! 🌟 بنرجع لهذا السؤال آخر الدرس، وبعدها بتقدر تشرحه بنفسك.',
     afterEn:'Great prediction! 🌟 We will come back to this question at the end — and then you will explain it yourself.'
   },
   essentialAr:'<b>السؤال الأساسي:</b> كيف ترتيب المادة وطاقة جزيئاتها تخلّيها صلبة أو سائلة أو غازية؟',
   essentialEn:'<b>Essential Question:</b> How does the structure of a substance and the energy of its particles relate to its properties in different states of matter?'
 },

 { id:'L1', icon:'📦', tagEn:'Lesson 1', tagAr:'الدرس ١',
   tEn:'What is matter?', tAr:'وش هي المادة؟', visual:'matterSort',
   arBody:'المادة = أي شي <b>له كتلة</b> و<b>يأخذ حيّز (مكان)</b>.<br>الكتاب 📕 والماء 💧 والهواء 💨 والصخرة 🪨 كلها مادة.<br>الضوء 💡 والصوت 🔊 ما لهم كتلة → مو مادة.',
   enBody:'Matter = anything that <b>has mass</b> and <b>takes up space</b>.<br>A book 📕, water 💧, air 💨 and a rock 🪨 are all matter.<br>Light 💡 and sound 🔊 have no mass → not matter.',
   quick:[
     {qEn:'What is matter?', qAr:'وش هي المادة؟', aEn:'Anything that has mass and takes up space.', aAr:'أي شي له كتلة ويأخذ حيّز.'},
     {qEn:'How do you know a book is made of matter?', qAr:'كيف تعرف أن الكتاب مادة؟', aEn:'A book occupies space and has mass.', aAr:'الكتاب يأخذ حيّز وله كتلة.'},
     {qEn:'Explain how air is matter.', qAr:'اشرح كيف الهواء مادة؟', aEn:'Air has mass and fills the space of its container — blow up a balloon and it takes up space.', aAr:'الهواء له كتلة ويملأ المكان — انفخ بالون وبيأخذ حيّز.'}
   ]
 },

 { id:'L2', icon:'🧊💧☁️', tagEn:'Lesson 2', tagAr:'الدرس ٢',
   tEn:'The three states of matter', tAr:'حالات المادة الثلاث', visual:'containers',
   arBody:'<b>صلب 🧊</b> شكل ثابت + حجم ثابت.<br><b>سائل 💧</b> يأخذ شكل الإناء + حجم ثابت.<br><b>غاز ☁️</b> لا شكل ثابت ولا حجم ثابت — يملأ الإناء كله.',
   enBody:'<b>Solid 🧊</b> definite shape + definite volume.<br><b>Liquid 💧</b> takes the shape of its container + definite volume.<br><b>Gas ☁️</b> no definite shape and no definite volume — it fills the whole container.'
 },

 { id:'L3', icon:'🔬', tagEn:'Lesson 3', tagAr:'الدرس ٣',
   tEn:'How particles move', tAr:'كيف تتحرك الجزيئات', visual:'threeStates',
   arBody:'<b>صلب:</b> الجزيئات قريبة جداً في تركيب صلب ثابت، <b>تهتز في مكانها</b> بس.<br><b>سائل:</b> قريبة من بعض، تتحرك حركة عشوائية وتتصادم و<b>تنزلق جنب بعض</b>.<br><b>غاز:</b> متباعدة جداً، تتحرك عشوائياً <b>بسرعة عالية</b>.',
   enBody:'<b>Solid:</b> particles are very close in a rigid structure and only <b>vibrate in place</b>.<br><b>Liquid:</b> particles are close together, move randomly, collide, and <b>slide past one another</b>.<br><b>Gas:</b> particles are widely spaced and move randomly at <b>high speeds</b>.',
   noteAr:'شوف الفرق يا عيسى 👀 — الصلب يهتز، السائل ينزلق، الغاز يطير.'
 },

 { id:'L4', icon:'🏃', tagEn:'Lesson 4', tagAr:'الدرس ٤',
   tEn:'Kinetic energy', tAr:'الطاقة الحركية', visual:'speedSim',
   arBody:'<b>الطاقة الحركية</b> = الطاقة اللي يملكها الجسم <b>بسبب حركته</b>.<br>تتحرك أسرع → طاقة حركية أكبر.',
   enBody:'<b>Kinetic energy</b> = the energy objects have <b>due to their motion</b>.<br>Faster movement → more kinetic energy.',
   trickAr:'🏃💨 KINETIC = حركة. إذا ما فيه حركة، ما فيه طاقة حركية.',
   trickEn:'🏃💨 KINETIC = motion. No motion, no kinetic energy.'
 },

 { id:'L5', icon:'🌡️', tagEn:'Lesson 5', tagAr:'الدرس ٥',
   tEn:'Temperature', tAr:'درجة الحرارة', visual:'thermoSim',
   arBody:'<b>درجة الحرارة تقيس متوسط الطاقة الحركية</b> لجزيئات المادة.<br>🔥 حرارة أعلى → الجزيئات أسرع → متوسط طاقة حركية أعلى.<br>❄️ حرارة أقل → الجزيئات أبطأ → متوسط طاقة حركية أقل.',
   enBody:'<b>Temperature measures the average kinetic energy</b> of the particles in a material.<br>🔥 Higher temperature → faster particles → higher average kinetic energy.<br>❄️ Lower temperature → slower particles → lower average kinetic energy.',
   trickAr:'الحرارة ↑ = حركة الجزيئات ↑ = متوسط الطاقة الحركية ↑',
   trickEn:'Temperature ↑ = particle motion ↑ = average kinetic energy ↑'
 },

 { id:'L6', icon:'📏', tagEn:'Lesson 6', tagAr:'الدرس ٦',
   tEn:'Thermometers & scales', tAr:'الترمومتر ومقاييس الحرارة', visual:'scales',
   arBody:'<b>الترمومتر</b> يقيس درجة الحرارة (أي متوسط الطاقة الحركية).<br>المقاييس: <b>سيليزيوس (C)</b>، <b>فهرنهايت (F)</b>، <b>كلفن (K)</b>. العلماء حول العالم يستخدمون سيليزيوس.<br><b>الصفر المطلق = 0 كلفن</b>: الدرجة اللي عندها تتوقف حركة الجزيئات تماماً وما يبقى عندها طاقة حركية.',
   enBody:'A <b>thermometer</b> measures temperature (the average kinetic energy).<br>Scales: <b>Celsius (C)</b>, <b>Fahrenheit (F)</b>, <b>Kelvin (K)</b>. Scientists worldwide use Celsius.<br><b>Absolute zero = 0 K</b>: the temperature at which particles stop all motion and have no kinetic energy.'
 },

 { id:'L7', icon:'🧲', tagEn:'Lesson 7', tagAr:'الدرس ٧',
   tEn:'Particle attraction', tAr:'قوى التجاذب بين الجزيئات', visual:'attract',
   arBody:'الجزيئات القريبة من بعض تسحب بعض (<b>قوى تجاذب</b>).<br><b>الصلب = أقوى تجاذب</b> · <b>السائل = تجاذب متوسط</b> · <b>الغاز = أضعف تجاذب</b>.',
   enBody:'Particles that are close together exert <b>attractive forces</b>.<br><b>Solid = strongest attraction</b> · <b>Liquid = moderate</b> · <b>Gas = weakest</b>.',
   trickAr:'كل ما قربوا أكثر → تجاذبهم أقوى.',
   trickEn:'The closer they are, the stronger they pull.'
 },

 { id:'L8', icon:'🔋', tagEn:'Lesson 8', tagAr:'الدرس ٨',
   tEn:'Potential energy', tAr:'طاقة الوضع (المخزنة)', visual:'potential',
   arBody:'<b>طاقة الوضع</b> = طاقة مخزّنة بسبب التفاعل بين الجزيئات.<br>كل ما كانت الجزيئات <b>أبعد عن بعض</b> → طاقة وضع <b>أكبر</b>.<br>لذلك <b>الغازات عندها طاقة وضع أكبر</b> من السوائل والمواد الصلبة، لأن جزيئاتها أبعد.',
   enBody:'<b>Potential energy</b> = stored energy due to interactions between particles.<br>Particles that are <b>farther apart</b> have <b>more</b> potential energy.<br>So <b>gases have more potential energy</b> than liquids or solids, because their particles are farther apart.',
   trickAr:'بعيدين = Potential أكثر 🔋',
   trickEn:'Farther apart = more potential 🔋'
 },

 { id:'L9', icon:'♨️', tagEn:'Lesson 9', tagAr:'الدرس ٩',
   tEn:'Thermal energy (this one is important!)', tAr:'الطاقة الحرارية (مهمة جداً!)', visual:'poolGlass',
   arBody:'<b>الطاقة الحرارية ≠ درجة الحرارة.</b><br>الطاقة الحرارية = <b>مجموع</b> الطاقة الناتجة عن حركة الجزيئات وتجاذبها = <b>طاقة حركية + طاقة وضع</b>.<br>تعتمد على: <b>درجة الحرارة</b> + <b>حالة المادة</b> + <b>كمية المادة</b>.',
   enBody:'<b>Thermal energy is NOT temperature.</b><br>Thermal energy = the <b>total</b> energy from particle motion and attractions = <b>kinetic + potential</b>.<br>It depends on: <b>temperature</b> + <b>state of matter</b> + <b>amount of matter</b>.',
   trickAr:'TEMPERATURE = متوسط 📉 · THERMAL ENERGY = المجموع ➕',
   trickEn:'TEMPERATURE = average 📉 · THERMAL ENERGY = total ➕'
 },

 { id:'L10', icon:'⚛️', tagEn:'Lesson 10', tagAr:'الدرس ١٠',
   tEn:'Atoms & substances', tAr:'الذرة والمادة النقية', visual:'atomSpin',
   arBody:'<b>الذرة</b> = جسيم صغير جداً، وهي <b>وحدة بناء المادة</b>.<br><b>المادة النقية (Substance)</b> = مادة تركيبها ثابت دائماً، ولها خصائص مميزة خاصة فيها.',
   enBody:'An <b>atom</b> is a small particle that is the <b>building block of matter</b>.<br>A <b>substance</b> is matter with a composition that is always the same, and it has unique properties.'
 },

 { id:'L11', icon:'🎨', tagEn:'Lesson 11', tagAr:'الدرس ١١',
   tEn:'How scientists model particles', tAr:'كيف يرسم العلماء الجزيئات', visual:'models',
   arBody:'العلماء يرسمون كل نوع ذرة <b>بلون وحجم مختلف</b>.<br>الهيليوم He = كرة وحدة. الكربون C = كرة وحدة بلون ثاني. الأكسجين O₂ = كرتين متشابهتين. الماء H₂O = كرة كبيرة + كرتين صغار.<br><b>وش تلاحظ؟</b> العنصر يتكوّن من نوع ذرة واحد، والمركب فيه أنواع مختلفة مرتبطة.',
   enBody:'Scientists draw each type of atom with a <b>different colour and size</b>.<br>Helium He = one sphere. Carbon C = one sphere in another colour. Oxygen O₂ = two identical spheres. Water H₂O = one big sphere + two small ones.<br><b>What do you notice?</b> An element shows only one kind of atom; a compound shows different kinds bonded together.'
 },

 { id:'L12', icon:'🔀', tagEn:'Lesson 12', tagAr:'الدرس ١٢',
   tEn:'Elements vs compounds', tAr:'العنصر والمركب', visual:'ecSort',
   arBody:'<b>العنصر</b> = مادة مكوّنة من <b>نوع واحد فقط</b> من الذرات (ممكن يكون صلب أو سائل أو غاز).<br><b>المركب</b> = ذرات من <b>عنصرين مختلفين أو أكثر</b> مرتبطة كيميائياً.<br>خصائص المركب تختلف عن خصائص عناصره.',
   enBody:'An <b>element</b> is a substance made of only <b>one type of atom</b> (it can be a solid, liquid or gas).<br>A <b>compound</b> forms when atoms of <b>two or more different elements</b> bond together.<br>A compound has different properties from its elements.'
 },

 { id:'L13', icon:'💧', tagEn:'Lesson 13', tagAr:'الدرس ١٣',
   tEn:'Element ratios', tAr:'نسب العناصر', visual:'ratio',
   arBody:'الماء دائماً بنسبة ثابتة: <b>٢ هيدروجين : ١ أكسجين</b> → H₂O.<br>نفس العناصر ممكن ترتبط بنسب مختلفة وتعطي مركبات مختلفة (مثل H₂O و H₂O₂).<br>اختلاف النسبة = اختلاف الخصائص وحالة المادة.',
   enBody:'Water always has a fixed ratio: <b>2 hydrogen : 1 oxygen</b> → H₂O.<br>The same elements can combine in different ratios to make different compounds (like H₂O and H₂O₂).<br>Different ratios give different properties and states of matter.'
 },

 { id:'L14', icon:'🔤', tagEn:'Lesson 14', tagAr:'الدرس ١٤',
   tEn:'Element symbols', tAr:'رموز العناصر', visual:'symbols',
   arBody:'رمز العنصر = حرف أو حرفين من اسمه في الجدول الدوري.<br>H = هيدروجين · O = أكسجين · C = كربون · N = نيتروجين · Na = صوديوم · Cl = كلور · He = هيليوم.',
   enBody:'An element symbol is one or two letters taken from the element name on the periodic table.<br>H = Hydrogen · O = Oxygen · C = Carbon · N = Nitrogen · Na = Sodium · Cl = Chlorine · He = Helium.'
 },

 { id:'L15', icon:'🧮', tagEn:'Lesson 15', tagAr:'الدرس ١٥',
   tEn:'Chemical formulas & subscripts', tAr:'الصيغ الكيميائية والأرقام الصغيرة', visual:'subscripts',
   arBody:'الصيغة الكيميائية تستخدم <b>الرموز + الأرقام</b> لتوضح عناصر المركب.<br>الرقم الصغير تحت (subscript) يبيّن <b>عدد ذرات العنصر اللي قبله</b>.<br><b>قاعدة ذهبية:</b> إذا ما فيه رقم صغير تحت العنصر، نحسبه <b>واحد</b>.<br>مثال CO₂ → C = ١ ذرة كربون، O₂ = ٢ ذرة أكسجين.',
   enBody:'A chemical formula uses <b>symbols + numbers</b> to show the elements in a compound.<br>The small number (subscript) shows <b>how many atoms of the element before it</b>.<br><b>Golden rule:</b> if there is no little number, count <b>ONE</b>.<br>Example CO₂ → C = 1 carbon atom, O₂ = 2 oxygen atoms.'
 }
];

/* ---------- BOOK 3-D THINKING CHALLENGES ---------- */
const THINK = [
 { id:'T1', visual:'twoGlasses',
   qEn:'Which contains the greatest amount of energy: a glass of water at 20°C or a glass of water at 80°C?',
   qAr:'مين فيه طاقة أكبر: كوب ماء ٢٠°م أو كوب ماء ٨٠°م؟',
   opts:[{en:'Glass at 20°C',ar:'الكوب ٢٠°م'},{en:'Glass at 80°C',ar:'الكوب ٨٠°م'},{en:'Exactly the same',ar:'نفس الشي بالضبط'}], ans:1,
   whyAr:'الكوب الأسخن (٨٠°م) جزيئاته تتحرك أسرع → متوسط طاقة حركية أعلى → طاقة أكبر. نفس الكمية ونفس المادة، والفرق الوحيد هو درجة الحرارة.',
   whyEn:'The hotter glass (80°C) has faster particles → higher average kinetic energy → more energy. Same amount, same substance, only the temperature differs.'},
 { id:'T2', visual:'twoCans',
   qEn:'Which contains the greatest amount of energy: an aluminum can at 30°C or an aluminum can at 20°C?',
   qAr:'مين فيه طاقة أكبر: علبة ألمنيوم ٣٠°م أو علبة ألمنيوم ٢٠°م؟',
   opts:[{en:'Can at 30°C',ar:'العلبة ٣٠°م'},{en:'Can at 20°C',ar:'العلبة ٢٠°م'},{en:'Cannot be compared',ar:'ما ينفع نقارن'}], ans:0,
   whyAr:'نفس العلبة ونفس المادة ونفس الكمية، لكن ٣٠°م أسخن → جزيئاتها أسرع → طاقة حركية أعلى → طاقة أكبر.',
   whyEn:'Same can, same material, same amount — but 30°C is hotter → faster particles → higher kinetic energy → more energy.'},
 { id:'T3', visual:'iceMelt',
   qEn:'Which has the greatest amount of energy: an ice cube at 0°C or a recently melted ice cube (water) at 0°C?',
   qAr:'مين فيه طاقة أكبر: مكعب ثلج عند ٠°م أو ثلج ذاب توّه (ماء) عند ٠°م؟',
   opts:[{en:'The ice cube at 0°C',ar:'مكعب الثلج ٠°م'},{en:'The melted water at 0°C',ar:'الماء الذايب ٠°م'},{en:'Equal, same temperature',ar:'متساوية، نفس الحرارة'}], ans:1,
   whyAr:'الاثنين نفس درجة الحرارة → نفس <b>متوسط الطاقة الحركية</b>. بس الماء الذايب صار <b>سائل</b>: جزيئاته تباعدت شوي وتحرّرت من التركيب الصلب، يعني <b>طاقة وضع أكبر</b>. والطاقة الحرارية = حركية + وضع، فالماء عنده طاقة أكبر. عشان كذا الثلج يحتاج طاقة عشان يذوب.',
   whyEn:'Both are at the same temperature → the same <b>average kinetic energy</b>. But the melted water is a <b>liquid</b>: its particles moved farther apart and escaped the rigid structure, so it has <b>more potential energy</b>. Thermal energy = kinetic + potential, so the melted water has more energy. That is why ice must absorb energy to melt.'},
 { id:'T4', visual:'particleModels',
   qEn:'Examine the models of Helium, Carbon, Oxygen and Water. What observations can you make about how different types of particles are modeled?',
   qAr:'شوف نماذج الهيليوم والكربون والأكسجين والماء. وش تلاحظ عن طريقة رسم أنواع الجسيمات المختلفة؟',
   opts:[
     {en:'Every atom is drawn exactly the same.',ar:'كل الذرات ترسم بنفس الشكل بالضبط.'},
     {en:'Each type of atom has its own colour and size; elements show one type of atom, compounds show different types joined.',ar:'كل نوع ذرة له لون وحجم خاص؛ العنصر فيه نوع ذرة واحد، والمركب فيه أنواع مختلفة مرتبطة.'},
     {en:'Only gases can be modeled.',ar:'الغازات بس اللي ينفع نرسمها.'}], ans:1,
   whyAr:'الهيليوم والكربون: كرة واحدة (عنصر، ذرة مفردة). الأكسجين O₂: كرتين <b>نفس اللون</b> (عنصر، جزيء من ذرتين متشابهتين). الماء H₂O: كرة كبيرة + كرتين صغار <b>بلون مختلف</b> (مركب).',
   whyEn:'Helium and Carbon: one sphere (an element, a single atom). Oxygen O₂: two spheres of the <b>same colour</b> (an element, a molecule of two identical atoms). Water H₂O: one big sphere + two small ones of a <b>different colour</b> (a compound).'}
];

/* ---------- QUESTION BANK (EVERY ITEM) ---------- */
const QB = [
/* ============ A. MULTIPLE CHOICE ============ */
{id:'A-1',sec:'A',type:'mcq',concept:'L3',
 qEn:'Which statement best describes the movement of particles in a liquid?',
 qAr:'أي عبارة تصف حركة الجزيئات في السائل بشكل أفضل؟',
 meanAr:'السؤال يبيك تعرف: <b>كيف تتحرك الجزيئات داخل السائل بالذات</b>، مو في الصلب ولا الغاز.',
 ideaAr:'شوف يا عيسى 👀 في السائل الجزيئات قريبة من بعض، بس مو ثابتة. تقدر تتحرك حركة عشوائية، تتصادم، وتنزلق جنب بعض.',
 ideaEn:'In a liquid the particles are close together but not fixed. They move around randomly, collide with each other, and slide past one another.',
 visual:'liquid',
 opts:[{en:'They are locked in a rigid structure and only vibrate in place.',ar:'محبوسة في تركيب صلب وتهتز في مكانها فقط.'},
       {en:'They are close together but can move around randomly and collide with each other.',ar:'قريبة من بعض لكن تتحرك عشوائياً وتتصادم مع بعض.'},
       {en:'They are widely spaced apart and move at extremely high speeds.',ar:'متباعدة جداً وتتحرك بسرعات عالية جداً.'},
       {en:'They stop moving completely when the temperature drops slightly.',ar:'تتوقف تماماً عن الحركة لما تنزل الحرارة شوي.'}],
 ans:1,
 whyAr:'لأن جزيئات السائل قريبة (عشان كذا حجمه ثابت) لكنها حرة تتحرك وتنزلق (عشان كذا يأخذ شكل الإناء).',
 whyEn:'Liquid particles are close together (so the volume is definite) but free to move and slide (so it takes the shape of its container).',
 wrong:{0:'هذا وصف الصلب 🧊 — الاهتزاز في المكان للصلب.',2:'هذا وصف الغاز ☁️ — التباعد والسرعة العالية للغاز.',3:'الجزيئات ما تتوقف إلا عند الصفر المطلق (0 كلفن).'},
 trickAr:'السائل = ينزلق 🏄 (قريب بس متحرك).', trickEn:'Liquid = slides 🏄 (close but moving).',
 chall:{qEn:'In which state do particles only vibrate in place?',qAr:'في أي حالة تهتز الجزيئات في مكانها فقط؟',
   opts:[{en:'Solid',ar:'الصلب'},{en:'Liquid',ar:'السائل'},{en:'Gas',ar:'الغاز'}],ans:0}},

{id:'A-2',sec:'A',type:'mcq',concept:'L5',
 qEn:'A scientist heats a sample of gas. What happens to the kinetic energy and temperature of the gas particles?',
 qAr:'عالم سخّن عيّنة غاز. وش يصير للطاقة الحركية ودرجة حرارة جزيئات الغاز؟',
 meanAr:'السؤال يبي يتأكد إنك عارف العلاقة: <b>تسخين ← حركة ← حرارة</b>.',
 ideaAr:'لما تسخّن، أنت تضيف طاقة. الجزيئات تتحرك أسرع → الطاقة الحركية تزيد → ودرجة الحرارة (اللي هي متوسط الطاقة الحركية) تزيد معها.',
 ideaEn:'Heating adds energy. Particles move faster → kinetic energy increases → and temperature (the average kinetic energy) increases too.',
 visual:'heatGas',
 opts:[{en:'Kinetic energy increases, and temperature increases.',ar:'الطاقة الحركية تزيد، ودرجة الحرارة تزيد.'},
       {en:'Kinetic energy decreases, and temperature increases.',ar:'الطاقة الحركية تقل، ودرجة الحرارة تزيد.'},
       {en:'Kinetic energy increases, and temperature decreases.',ar:'الطاقة الحركية تزيد، ودرجة الحرارة تقل.'},
       {en:'Both kinetic energy and temperature stay exactly the same.',ar:'الاثنتين تبقى نفسها بالضبط.'}],
 ans:0,
 whyAr:'لأن درجة الحرارة <b>هي</b> مقياس متوسط الطاقة الحركية، فلازم يزيدون مع بعض في نفس الاتجاه.',
 whyEn:'Temperature <b>is</b> the measure of average kinetic energy, so they must rise together.',
 wrong:{1:'مستحيل تقل الحركة وترتفع الحرارة — هم مربوطين ببعض.',2:'نفس الشي بالعكس، ما ينفصلون.',3:'التسخين لازم يغيّر شي — يضيف طاقة.'},
 trickAr:'سخّن = سرّع 🔥🏃 (الاثنين يطلعون فوق مع بعض).', trickEn:'Heat = speed 🔥🏃 (both go up together).',
 chall:{qEn:'If you cool a gas, its average kinetic energy…',qAr:'إذا برّدت الغاز، متوسط طاقته الحركية…',
   opts:[{en:'Decreases',ar:'يقل'},{en:'Increases',ar:'يزيد'},{en:'Stays the same',ar:'يبقى نفسه'}],ans:0}},

{id:'A-3',sec:'A',type:'mcq',concept:'L8',
 qEn:'Why do gases have a higher energy compared to liquids and solids?',
 qAr:'ليش الغازات عندها طاقة أعلى مقارنة بالسوائل والمواد الصلبة؟',
 meanAr:'السؤال عن <b>طاقة الوضع</b> — الطاقة المخزّنة بسبب المسافة بين الجزيئات.',
 ideaAr:'الدرس يقول: كل ما كانت الجزيئات أبعد عن بعض، طاقة الوضع أكبر. وجزيئات الغاز هي الأبعد → عندها أكبر طاقة وضع.',
 ideaEn:'The lesson says: particles that are farther apart have more potential energy. Gas particles are the farthest apart → they have the most potential energy.',
 visual:'potential',
 opts:[{en:'Gas particles are packed very tightly together.',ar:'جزيئات الغاز متراصة بشدة.'},
       {en:'Gas particles have the strongest attractive forces.',ar:'جزيئات الغاز عندها أقوى قوى تجاذب.'},
       {en:'Gas particles are spaced much farther apart from each other.',ar:'جزيئات الغاز متباعدة عن بعض بمسافات أكبر بكثير.'},
       {en:'Gas particles do not contain any atoms.',ar:'جزيئات الغاز ما تحتوي ذرات.'}],
 ans:2,
 whyAr:'لأن البُعد بين الجزيئات = طاقة وضع مخزّنة أكبر.',
 whyEn:'Distance between particles = more stored potential energy.',
 wrong:{0:'العكس — المتراص هو الصلب.',1:'أقوى تجاذب للصلب، والغاز عنده الأضعف.',3:'كل مادة مكوّنة من ذرات، حتى الغاز.'},
 trickAr:'بعيدين = Potential أكثر 🔋', trickEn:'Farther apart = more potential 🔋',
 chall:{qEn:'Which state has the weakest attraction between particles?',qAr:'أي حالة فيها أضعف تجاذب بين الجزيئات؟',
   opts:[{en:'Gas',ar:'الغاز'},{en:'Liquid',ar:'السائل'},{en:'Solid',ar:'الصلب'}],ans:0}},

{id:'A-4',sec:'A',type:'mcq',concept:'L15',
 qEn:'Look at the chemical formula for methane gas: CH₄. What does the subscript number 4 tell you?',
 qAr:'شوف صيغة غاز الميثان: CH₄. وش يعني الرقم الصغير ٤؟',
 meanAr:'السؤال يبيك تقرأ <b>الرقم الصغير</b> وتعرف على أي عنصر يرجع.',
 ideaAr:'الرقم الصغير يخص <b>العنصر اللي قبله مباشرة</b>. الـ ٤ جنب H، يعني ٤ ذرات هيدروجين. والـ C ما عنده رقم → ذرة كربون وحدة.',
 ideaEn:'A subscript belongs to the element <b>right before it</b>. The 4 is next to H, so 4 hydrogen atoms. C has no number → 1 carbon atom.',
 visual:'ch4',
 opts:[{en:'There are 4 carbon atoms in each molecule.',ar:'يوجد ٤ ذرات كربون في كل جزيء.'},
       {en:'There are 4 hydrogen atoms in each molecule.',ar:'يوجد ٤ ذرات هيدروجين في كل جزيء.'},
       {en:'The molecule is in a solid state of matter.',ar:'الجزيء في الحالة الصلبة.'},
       {en:'There are 4 different elements combined together.',ar:'يوجد ٤ عناصر مختلفة مرتبطة.'}],
 ans:1,
 whyAr:'CH₄ = ذرة كربون واحدة + أربع ذرات هيدروجين. المجموع ٥ ذرات.',
 whyEn:'CH₄ = one carbon atom + four hydrogen atoms. Five atoms in total.',
 wrong:{0:'الـ ٤ ملتصق بـ H مو بـ C.',2:'الصيغة ما تخبرنا عن حالة المادة.',3:'العناصر هنا اثنين بس: C و H.'},
 trickAr:'الرقم الصغير يمسك يد العنصر اللي قبله ✋', trickEn:'The little number holds the hand of the letter before it ✋',
 chall:{qEn:'How many carbon atoms are in CH₄?',qAr:'كم ذرة كربون في CH₄؟',
   opts:[{en:'1',ar:'١'},{en:'4',ar:'٤'},{en:'5',ar:'٥'}],ans:0}},

{id:'A-5',sec:'A',type:'mcq',concept:'L3',
 qEn:'Which statement best describes the arrangement and movement of particles in a liquid?',
 qAr:'أي عبارة تصف ترتيب وحركة الجزيئات في السائل بشكل أفضل؟',
 meanAr:'هنا السؤال يجمع شيئين: <b>الترتيب</b> (قريبة؟ بعيدة؟) و<b>الحركة</b> (تهتز؟ تنزلق؟).',
 ideaAr:'الترتيب: قريبة من بعض بدون نظام ثابت. الحركة: تنزلق وتمر جنب بعض.',
 ideaEn:'Arrangement: close together with no fixed pattern. Movement: they slide past one another.',
 visual:'liquid',
 opts:[{en:'Particles are tightly packed and only vibrate in fixed positions.',ar:'متراصة بإحكام وتهتز في مواضع ثابتة فقط.'},
       {en:'Particles are close together but can slide past one another.',ar:'قريبة من بعض لكن تقدر تنزلق جنب بعض.'},
       {en:'Particles are far apart and move rapidly in all directions.',ar:'متباعدة وتتحرك بسرعة في كل الاتجاهات.'},
       {en:'Particles have no attraction to each other and fill the entire container.',ar:'ما بينها تجاذب وتملأ الإناء كله.'}],
 ans:1,
 whyAr:'الانزلاق هو سر السائل: قريب مثل الصلب لكنه يجري ويأخذ شكل الإناء.',
 whyEn:'Sliding is the secret of a liquid: as close as a solid, but it flows and takes the container shape.',
 wrong:{0:'وصف الصلب.',2:'وصف الغاز.',3:'السائل عنده تجاذب متوسط، ومو يملأ الإناء كله.'},
 trickAr:'تخيّل كرات زجاجية في كيس: قريبة بس تتزحلق 🫧', trickEn:'Imagine marbles in a bag: close, but sliding 🫧',
 chall:{qEn:'A liquid has a definite…',qAr:'السائل له … ثابت',
   opts:[{en:'Volume',ar:'حجم'},{en:'Shape',ar:'شكل'},{en:'Both',ar:'الاثنين'}],ans:0}},

{id:'A-6',sec:'A',type:'mcq',concept:'L9',
 qEn:'When a substance changes from a gas to a liquid, what happens to the energy and arrangement of its particles?',
 qAr:'لما تتحول المادة من غاز إلى سائل، وش يصير لطاقة جزيئاتها وترتيبها؟',
 meanAr:'السؤال عن <b>التكاثف Condensation</b>: غاز → سائل.',
 ideaAr:'عشان الغاز يصير سائل لازم <b>يبرد</b>: يفقد طاقة حرارية → الجزيئات تبطئ → تقترب من بعض → تصير سائل. هذا اسمه التكاثف.',
 ideaEn:'For a gas to become a liquid it must <b>cool</b>: it loses thermal energy → particles slow down → they move closer together → liquid. This is condensation.',
 visual:'condense',
 opts:[{en:'Particles gain thermal energy and move further apart.',ar:'تكتسب طاقة حرارية وتتباعد أكثر.'},
       {en:'Particles lose thermal energy and become fixed in a rigid structure.',ar:'تفقد طاقة حرارية وتثبت في تركيب صلب.'},
       {en:'Particles lose thermal energy and move closer together as condensation occurs.',ar:'تفقد طاقة حرارية وتقترب من بعض ويحصل تكاثف.'},
       {en:'Particles maintain the same thermal energy while changing speed randomly.',ar:'تحافظ على نفس الطاقة الحرارية مع تغير سرعتها عشوائياً.'}],
 ans:2,
 whyAr:'التكاثف = فقدان طاقة + تقارب الجزيئات، لكنها تبقى تنزلق (سائل) ومو ثابتة (صلب).',
 whyEn:'Condensation = losing energy + particles moving closer, but they still slide (liquid), they are not fixed (solid).',
 wrong:{0:'اكتساب طاقة وتباعد = تبخّر، عكس المطلوب.',1:'التركيب الصلب الثابت = تجمّد، مو تكاثف.',3:'لو ما تغيرت الطاقة، ما تتغير الحالة.'},
 trickAr:'برد كوب الماء ← قطرات على الكوب = تكاثف 💧', trickEn:'Cold glass ← droplets appear = condensation 💧',
 chall:{qEn:'Liquid → gas when a substance…',qAr:'سائل ← غاز لما المادة…',
   opts:[{en:'Gains thermal energy',ar:'تكتسب طاقة حرارية'},{en:'Loses thermal energy',ar:'تفقد طاقة حرارية'}],ans:0}},

{id:'A-7',sec:'A',type:'mcq',concept:'L4',
 qEn:'How does increasing the temperature of a gas inside a closed, rigid container affect the motion of its particles?',
 qAr:'كيف تؤثر زيادة حرارة غاز داخل إناء مغلق وصلب على حركة جزيئاته؟',
 meanAr:'كلمة <b>rigid = صلب ما يتمدد</b>. يعني الجزيئات ما تقدر تهرب، فوش يصير؟',
 ideaAr:'الحرارة تزيد → الجزيئات تتحرك أسرع → تضرب جدران الإناء <b>أكثر وأقوى</b> (وهذا يزيد الضغط).',
 ideaEn:'Temperature up → particles move faster → they hit the container walls <b>more often and harder</b> (this raises the pressure).',
 visual:'rigidBox',
 opts:[{en:'The particles move faster and collide with the container walls more forcefully.',ar:'تتحرك أسرع وتصطدم بجدران الإناء بقوة أكبر.'},
       {en:'The particles slow down and stop moving completely.',ar:'تبطئ وتتوقف عن الحركة تماماً.'},
       {en:'The size of individual particles increases, causing them to spread out.',ar:'حجم كل جسيم يكبر فيتباعدون.'},
       {en:'The particles stop colliding with each other because they lose attraction.',ar:'تتوقف عن التصادم لأنها تفقد التجاذب.'}],
 ans:0,
 whyAr:'التسخين يعطي طاقة حركية، والإناء مقفل، فالتصادمات تزيد عدداً وقوة.',
 whyEn:'Heating adds kinetic energy, and the container is closed, so collisions become more frequent and forceful.',
 wrong:{1:'التسخين يسرّع، ما يبطّئ.',2:'الجزيئات نفسها ما يكبر حجمها — المسافات بينها هي اللي تتغير.',3:'أسرع = تصادم أكثر، مو أقل.'},
 trickAr:'إناء مقفل + حرارة = ضرب أقوى على الجدران 💥', trickEn:'Closed box + heat = harder hits on the walls 💥',
 chall:{qEn:'In a rigid closed container, heating a gas raises…',qAr:'في إناء مقفل صلب، تسخين الغاز يرفع…',
   opts:[{en:'The pressure on the walls',ar:'الضغط على الجدران'},{en:'The size of each particle',ar:'حجم كل جسيم'}],ans:0}},

{id:'A-8',sec:'A',type:'mcq',concept:'L9',
 qEn:'When you hold a warm mug of hot chocolate, your hands feel warm. In which direction does the thermal energy flow?',
 qAr:'لما تمسك كوب شوكولاتة ساخنة، يداك تحس بالدفء. الطاقة الحرارية تنتقل في أي اتجاه؟',
 meanAr:'السؤال: <b>الحرارة وين بتروح؟</b> من الساخن للبارد، ولا العكس؟',
 ideaAr:'الطاقة الحرارية دائماً تنتقل من <b>الأسخن → الأبرد</b>. الكوب أسخن من يدك، فالطاقة تروح من الكوب ليدك.',
 ideaEn:'Thermal energy always flows from <b>hotter → cooler</b>. The mug is hotter than your hand, so energy moves from the mug into your hand.',
 visual:'mug',
 opts:[{en:'From your hands to the mug, because your hands have more total surface area.',ar:'من يدك للكوب، لأن مساحة يدك أكبر.'},
       {en:'Thermal energy does not flow; it stays trapped inside the ceramic mug.',ar:'الطاقة ما تنتقل؛ تبقى محبوسة داخل الكوب.'},
       {en:'From the surrounding room air into your hands.',ar:'من هواء الغرفة إلى يديك.'},
       {en:'From the hot mug into your cooler hands.',ar:'من الكوب الساخن إلى يديك الأبرد.'}],
 ans:3,
 whyAr:'لأن جزيئات الكوب الساخنة تصطدم بجزيئات يدك وتنقل لها طاقة حركية، فتحس بالدفء.',
 whyEn:'The hot mug particles collide with the particles in your hand and transfer kinetic energy, so your hand feels warm.',
 wrong:{0:'المساحة ما تحدد الاتجاه — الحرارة هي اللي تحدد.',1:'لو ما انتقلت، ما حسيت بالدفء أصلاً.',2:'هواء الغرفة أبرد من الكوب، ومو هو مصدر الدفء هنا.'},
 trickAr:'🔥 ← ❄️ دايماً من الساخن للبارد.', trickEn:'🔥 → ❄️ always hot to cold.',
 chall:{qEn:'Ice cube in your hand: energy flows…',qAr:'مكعب ثلج بيدك: الطاقة تنتقل…',
   opts:[{en:'From your hand to the ice',ar:'من يدك إلى الثلج'},{en:'From the ice to your hand',ar:'من الثلج إلى يدك'}],ans:0}},

{id:'A-9',sec:'A',type:'mcq',concept:'L12',
 qEn:'Water (H₂O) and table salt (NaCl) are common household substances. How should they be classified?',
 qAr:'الماء (H₂O) وملح الطعام (NaCl) مواد موجودة في كل بيت. كيف نصنّفها؟',
 meanAr:'السؤال يبيك تقرر: عنصر؟ مركب؟ مخلوط؟ — وتعرف <b>ليش</b>.',
 ideaAr:'كل وحدة منها مكوّنة من <b>عنصرين مختلفين</b> مرتبطين كيميائياً بنسبة ثابتة → مركبات. H₂O = هيدروجين + أكسجين. NaCl = صوديوم + كلور.',
 ideaEn:'Each one is made of <b>two different elements</b> chemically bonded in a fixed ratio → compounds. H₂O = hydrogen + oxygen. NaCl = sodium + chlorine.',
 visual:'h2onacl',
 opts:[{en:'As elements, because they are pure substances found in nature.',ar:'عناصر، لأنها مواد نقية موجودة في الطبيعة.'},
       {en:'As mixtures, because they can be easily separated by physical filtration.',ar:'مخاليط، لأنها تنفصل بالترشيح بسهولة.'},
       {en:'As compounds, because each is made of two or more different elements chemically combined in a fixed ratio.',ar:'مركبات، لأن كل وحدة مكوّنة من عنصرين مختلفين أو أكثر مرتبطين كيميائياً بنسبة ثابتة.'},
       {en:'As heterogeneous solutions, because they contain multiple visible phases.',ar:'محاليل غير متجانسة، لأنها تحتوي أطوار مرئية متعددة.'}],
 ans:2,
 whyAr:'لأن الشرط للمركب = عنصران مختلفان أو أكثر + ارتباط كيميائي + نسبة ثابتة. الثلاثة متحققة.',
 whyEn:'A compound needs two or more different elements + a chemical bond + a fixed ratio. All three are true here.',
 wrong:{0:'العنصر نوع ذرة واحد فقط، وهنا نوعين.',1:'المخلوط ينفصل فيزيائياً، أما الرابطة الكيميائية فلا.',3:'الماء والملح موحّدان، مو أطوار مرئية متعددة.'},
 trickAr:'حرفين مختلفين في الصيغة = مركب 🔗', trickEn:'Two different letters in the formula = compound 🔗',
 chall:{qEn:'Is O₂ an element or a compound?',qAr:'هل O₂ عنصر أو مركب؟',
   opts:[{en:'Element (one type of atom)',ar:'عنصر (نوع ذرة واحد)'},{en:'Compound',ar:'مركب'}],ans:0}},

{id:'A-10',sec:'A',type:'mcq',concept:'L12',
 qEn:'How can you best distinguish a chemical element from a chemical compound?',
 qAr:'كيف تفرّق بين العنصر والمركب بأفضل طريقة؟',
 meanAr:'السؤال يبي <b>التعريف الفاصل</b> بين الاثنين.',
 ideaAr:'العنصر = نوع ذرة <b>واحد</b> فقط. المركب = نوعان مختلفان أو أكثر <b>مرتبطين كيميائياً</b>.',
 ideaEn:'Element = only <b>one</b> type of atom. Compound = two or more different types of atoms <b>chemically bonded</b>.',
 visual:'ecSort',
 opts:[{en:'An element consists of only one type of atom, whereas a compound consists of two or more different types of atoms chemically bonded.',ar:'العنصر نوع ذرة واحد فقط، والمركب نوعان مختلفان أو أكثر مرتبطان كيميائياً.'},
       {en:'An element can be broken down into simpler substances by physical means, but a compound cannot.',ar:'العنصر ينكسر لمواد أبسط بطرق فيزيائية، والمركب لا.'},
       {en:'An element is always a gas at room temperature, while a compound is always a solid.',ar:'العنصر دائماً غاز والمركب دائماً صلب.'},
       {en:'An element contains molecules, whereas a compound contains only isolated free electrons.',ar:'العنصر يحتوي جزيئات والمركب يحتوي إلكترونات حرة فقط.'}],
 ans:0,
 whyAr:'هذا هو التعريف الصحيح من الدرس تماماً: عدد <b>أنواع</b> الذرات هو الفرق.',
 whyEn:'This matches the lesson definition exactly: the number of <b>types</b> of atoms is the difference.',
 wrong:{1:'معكوسة — العنصر هو اللي ما ينكسر لمواد أبسط.',2:'العناصر ممكن تكون صلبة أو سائلة أو غازية (الحديد صلب!).',3:'كلام غير صحيح علمياً.'},
 trickAr:'عنصر = لون واحد 🔵🔵 · مركب = ألوان مختلفة 🔴🔵', trickEn:'Element = one colour 🔵🔵 · Compound = different colours 🔴🔵',
 chall:{qEn:'Iron (Fe) is a solid. Is it an element?',qAr:'الحديد (Fe) صلب. هل هو عنصر؟',
   opts:[{en:'Yes — one type of atom',ar:'نعم — نوع ذرة واحد'},{en:'No — solids cannot be elements',ar:'لا — الصلب ما يكون عنصر'}],ans:0}},

/* ============ B. DIRECT COMPARISON ============ */
{id:'B-1',sec:'B',type:'mcq',concept:'L2',
 qEn:'Direct comparison — SHAPE: complete the row for solids, liquids and gases.',
 qAr:'مقارنة مباشرة — الشكل: أكمل صف الشكل للصلب والسائل والغاز.',
 meanAr:'السؤال يبي تعبّي جدول المقارنة: خانة <b>الشكل</b> للحالات الثلاث.',
 ideaAr:'الصلب يحافظ على شكله في أي إناء. السائل يأخذ شكل الإناء. الغاز ما له شكل ثابت أبداً.',
 ideaEn:'A solid keeps its shape in any container. A liquid takes the container shape. A gas has no definite shape at all.',
 visual:'containers',
 opts:[{en:'Solid: definite shape · Liquid: takes the shape of its container · Gas: no definite shape',ar:'صلب: شكل ثابت · سائل: يأخذ شكل الإناء · غاز: لا شكل ثابت'},
       {en:'Solid: no definite shape · Liquid: definite shape · Gas: definite shape',ar:'صلب: لا شكل ثابت · سائل: شكل ثابت · غاز: شكل ثابت'},
       {en:'All three keep a definite shape',ar:'الثلاثة كلها تحافظ على شكل ثابت'}],
 ans:0,
 whyAr:'لأن جزيئات الصلب مقفّلة في مكانها، وجزيئات السائل تنزلق فتتشكل حسب الإناء، وجزيئات الغاز تطير في كل الاتجاهات.',
 whyEn:'Solid particles are locked in place, liquid particles slide so they fit the container, gas particles fly everywhere.',
 trickAr:'صلب = عنيد 🧊 · سائل = متكيّف 💧 · غاز = حر ☁️', trickEn:'Solid = stubborn 🧊 · Liquid = adapts 💧 · Gas = free ☁️',
 chall:{qEn:'Pour juice into a tall glass. Its shape…',qAr:'صبّ عصير في كوب طويل. شكله…',
   opts:[{en:'Becomes the glass shape',ar:'يصير شكل الكوب'},{en:'Stays the same',ar:'يبقى نفسه'}],ans:0}},

{id:'B-2',sec:'B',type:'mcq',concept:'L2',
 qEn:'Direct comparison — VOLUME: complete the row for solids, liquids and gases.',
 qAr:'مقارنة مباشرة — الحجم: أكمل صف الحجم للحالات الثلاث.',
 meanAr:'خانة <b>الحجم</b> في جدول المقارنة.',
 ideaAr:'الصلب: حجم ثابت. السائل: حجم ثابت أيضاً (لتر ماء يبقى لتر). الغاز: لا حجم ثابت — يتمدد ليملأ الإناء.',
 ideaEn:'Solid: definite volume. Liquid: definite volume too (a litre of water stays a litre). Gas: no definite volume — it expands to fill the container.',
 visual:'containers',
 opts:[{en:'Solid: definite · Liquid: definite · Gas: no definite volume',ar:'صلب: ثابت · سائل: ثابت · غاز: غير ثابت'},
       {en:'Solid: definite · Liquid: no definite volume · Gas: definite',ar:'صلب: ثابت · سائل: غير ثابت · غاز: ثابت'},
       {en:'None of them has a definite volume',ar:'ولا وحدة منها لها حجم ثابت'}],
 ans:0,
 whyAr:'الصلب والسائل جزيئاتهما قريبة فما ينضغطون كثير → حجم ثابت. الغاز جزيئاته متباعدة فيتمدد أو ينضغط.',
 whyEn:'Solid and liquid particles are close, so they keep a definite volume. Gas particles are far apart, so the gas expands or squeezes.',
 trickAr:'الحجم الثابت لاثنين (صلب وسائل)، والغاز بس هو المتفلّت 🎈', trickEn:'Two keep volume (solid + liquid); only gas escapes 🎈',
 chall:{qEn:'A gas in a big box will…',qAr:'الغاز في صندوق كبير…',
   opts:[{en:'Fill the whole box',ar:'يملأ الصندوق كله'},{en:'Stay in one corner',ar:'يبقى في زاوية'}],ans:0}},

{id:'B-3',sec:'B',type:'mcq',concept:'L7',
 qEn:'Direct comparison — PARTICLE ATTRACTION: complete the row for solids, liquids and gases.',
 qAr:'مقارنة مباشرة — قوى التجاذب: أكمل الصف للحالات الثلاث.',
 meanAr:'خانة <b>التجاذب بين الجزيئات</b>: مين الأقوى ومين الأضعف؟',
 ideaAr:'كل ما قربت الجزيئات زاد التجاذب. الصلب أقرب → <b>أقوى تجاذب</b>. السائل → <b>متوسط</b>. الغاز أبعد → <b>أضعف تجاذب</b>.',
 ideaEn:'The closer the particles, the stronger the attraction. Solid is closest → <b>strongest</b>. Liquid → <b>moderate</b>. Gas is farthest → <b>weakest</b>.',
 visual:'attract',
 opts:[{en:'Solid: strongest · Liquid: moderate · Gas: weakest',ar:'صلب: الأقوى · سائل: متوسط · غاز: الأضعف'},
       {en:'Solid: weakest · Liquid: moderate · Gas: strongest',ar:'صلب: الأضعف · سائل: متوسط · غاز: الأقوى'},
       {en:'All three have equal attraction',ar:'الثلاثة تجاذبها متساوٍ'}],
 ans:0,
 whyAr:'التجاذب يعتمد على المسافة، والمسافة أصغر شي في الصلب وأكبر شي في الغاز.',
 whyEn:'Attraction depends on distance: smallest distance in a solid, largest in a gas.',
 trickAr:'قريب = يشد أقوى 🧲', trickEn:'Closer = stronger pull 🧲',
 chall:{qEn:'Strong attraction + vibrating in place =',qAr:'تجاذب قوي + اهتزاز في المكان =',
   opts:[{en:'Solid',ar:'صلب'},{en:'Gas',ar:'غاز'}],ans:0}},

/* ============ C. DEFINE THE TERM ============ */
{id:'C-1',sec:'C',type:'define',concept:'L4',
 qEn:'Define: Kinetic energy',qAr:'عرّف: الطاقة الحركية',
 meanAr:'السؤال يبي <b>تعريف دقيق</b> تكتبه في الاختبار.',
 ideaAr:'أي شي يتحرك عنده طاقة حركية. وقف الحركة → راحت الطاقة الحركية.',
 ideaEn:'Anything that moves has kinetic energy. Stop the motion and the kinetic energy is gone.',
 answerEn:'The energy objects have due to their motion.',
 answerAr:'الطاقة التي تمتلكها الأجسام بسبب حركتها.',
 opts:[{en:'The energy objects have due to their motion.',ar:'الطاقة التي تمتلكها الأجسام بسبب حركتها.'},
       {en:'Stored energy due to interactions between particles.',ar:'طاقة مخزنة بسبب التفاعل بين الجزيئات.'},
       {en:'The total energy from particle motion and attractions.',ar:'مجموع الطاقة من حركة الجزيئات وتجاذبها.'}],
 ans:0, visual:'speedSim',
 whyAr:'كلمة المفتاح هي <b>الحركة (motion)</b>.',whyEn:'The key word is <b>motion</b>.',
 trickAr:'KINETIC = حركة 🏃',trickEn:'KINETIC = motion 🏃',
 chall:{qEn:'A parked car has kinetic energy?',qAr:'سيارة واقفة عندها طاقة حركية؟',opts:[{en:'No',ar:'لا'},{en:'Yes',ar:'نعم'}],ans:0}},

{id:'C-2',sec:'C',type:'define',concept:'L9',
 qEn:'Define: Thermal energy',qAr:'عرّف: الطاقة الحرارية',
 meanAr:'انتبه: هذا التعريف فيه كلمة <b>total (مجموع)</b> وهي المفتاح.',
 ideaAr:'الطاقة الحرارية تجمع كل شي: حركة الجزيئات + التجاذب بينها، في المادة كلها.',
 ideaEn:'Thermal energy adds everything up: particle motion + attractions, across the whole substance.',
 answerEn:'The total energy from particle motion and attractions in a substance.',
 answerAr:'مجموع الطاقة الناتجة عن حركة الجزيئات وقوى التجاذب بينها في المادة.',
 opts:[{en:'The total energy from particle motion and attractions in a substance.',ar:'مجموع الطاقة الناتجة عن حركة الجزيئات وقوى التجاذب في المادة.'},
       {en:'The average kinetic energy of particles.',ar:'متوسط الطاقة الحركية للجزيئات.'},
       {en:'The energy of an object because of its position.',ar:'طاقة الجسم بسبب موقعه.'}],
 ans:0, visual:'poolGlass',
 whyAr:'الخيار الثاني هو تعريف <b>درجة الحرارة</b> مو الطاقة الحرارية. الحرارة = متوسط، الطاقة الحرارية = مجموع.',
 whyEn:'The second option defines <b>temperature</b>, not thermal energy. Temperature = average, thermal energy = total.',
 trickAr:'Thermal = Total ➕ (الاثنين بحرف T)',trickEn:'Thermal = Total ➕ (both start with T)',
 chall:{qEn:'Bigger sample at the same temperature has…',qAr:'كمية أكبر عند نفس الحرارة عندها…',
   opts:[{en:'More thermal energy',ar:'طاقة حرارية أكبر'},{en:'Higher temperature',ar:'درجة حرارة أعلى'}],ans:0}},

{id:'C-3',sec:'C',type:'define',concept:'L8',
 qEn:'Define: Potential energy',qAr:'عرّف: طاقة الوضع',
 meanAr:'كلمة المفتاح: <b>مخزّنة (stored)</b>.',
 ideaAr:'طاقة مخزّنة بسبب التفاعل والمسافة بين الجزيئات. كل ما تباعدوا زادت.',
 ideaEn:'Stored energy from the interaction and spacing between particles. More distance, more potential energy.',
 answerEn:'Stored energy due to interactions between particles.',
 answerAr:'طاقة مخزّنة ناتجة عن التفاعل بين الجزيئات.',
 opts:[{en:'Stored energy due to interactions between particles.',ar:'طاقة مخزّنة ناتجة عن التفاعل بين الجزيئات.'},
       {en:'Energy due to motion only.',ar:'طاقة بسبب الحركة فقط.'},
       {en:'The temperature of a substance.',ar:'درجة حرارة المادة.'}],
 ans:0, visual:'potential',
 whyAr:'لأنها ما تعتمد على السرعة، تعتمد على الوضع والمسافة.',whyEn:'It does not depend on speed; it depends on position and distance.',
 trickAr:'بعيدين = Potential أكثر 🔋',trickEn:'Farther apart = more potential 🔋',
 chall:{qEn:'Which state has the most potential energy?',qAr:'أي حالة عندها أكبر طاقة وضع؟',
   opts:[{en:'Gas',ar:'الغاز'},{en:'Solid',ar:'الصلب'}],ans:0}},

{id:'C-4',sec:'C',type:'define',concept:'L12',
 qEn:'Define: Element',qAr:'عرّف: العنصر',
 meanAr:'يبي التعريف بالضبط: كم <b>نوع</b> ذرة؟',
 ideaAr:'العنصر مادة مكوّنة من نوع ذرة واحد فقط، مثل الأكسجين O أو الذهب Au.',
 ideaEn:'An element is a substance made of only one type of atom, like oxygen O or gold Au.',
 answerEn:'A substance made of only one type of atom.',
 answerAr:'مادة مكوّنة من نوع واحد فقط من الذرات.',
 opts:[{en:'A substance made of only one type of atom.',ar:'مادة مكوّنة من نوع واحد فقط من الذرات.'},
       {en:'Two or more different atoms bonded together.',ar:'ذرتان مختلفتان أو أكثر مرتبطتان.'},
       {en:'Anything that has mass and takes up space.',ar:'أي شي له كتلة ويأخذ حيّز.'}],
 ans:0, visual:'ecSort',
 whyAr:'الخيار الثاني تعريف المركب، والثالث تعريف المادة.',whyEn:'Option two defines a compound; option three defines matter.',
 trickAr:'عنصر = نوع واحد 1️⃣',trickEn:'Element = one type 1️⃣',
 chall:{qEn:'He (helium) is…',qAr:'الهيليوم He هو…',opts:[{en:'An element',ar:'عنصر'},{en:'A compound',ar:'مركب'}],ans:0}},

{id:'C-5',sec:'C',type:'define',concept:'L10',
 qEn:'Define: Atom',qAr:'عرّف: الذرة',
 meanAr:'يبي جملة قصيرة: وش هي الذرة؟',
 ideaAr:'الذرة جسيم صغير جداً، وهي وحدة بناء كل المواد — مثل قطعة الليقو 🧱.',
 ideaEn:'An atom is a very small particle and it is the building block of all matter — like a LEGO brick 🧱.',
 answerEn:'A small particle that is the building block of matter.',
 answerAr:'جسيم صغير يُعدّ وحدة بناء المادة.',
 opts:[{en:'A small particle that is the building block of matter.',ar:'جسيم صغير يُعدّ وحدة بناء المادة.'},
       {en:'A mixture of two liquids.',ar:'خليط من سائلين.'},
       {en:'A unit for measuring temperature.',ar:'وحدة لقياس درجة الحرارة.'}],
 ans:0, visual:'atomSpin',
 whyAr:'الكلمة المفتاح: <b>وحدة بناء المادة</b>.',whyEn:'Key phrase: <b>building block of matter</b>.',
 trickAr:'الذرة = ليقو الكون 🧱',trickEn:'Atom = the LEGO of the universe 🧱',
 chall:{qEn:'Atoms join to make…',qAr:'الذرات ترتبط لتكوّن…',opts:[{en:'Molecules and compounds',ar:'جزيئات ومركبات'},{en:'Temperature',ar:'درجة حرارة'}],ans:0}},

/* ============ D. ANSWER THE FOLLOWING ============ */
{id:'D-1',sec:'D',type:'mcq',concept:'L1',
 qEn:'How do you know that a book is matter?',qAr:'كيف تعرف أن الكتاب مادة؟',
 meanAr:'السؤال يبي <b>دليلين</b>: الكتلة والحيّز.',
 ideaAr:'أي شي مادة لازم يحقق شرطين: له كتلة (نقدر نوزنه) ويأخذ حيّز (يحتل مكان على الرف).',
 ideaEn:'Anything that is matter must satisfy two tests: it has mass (we can weigh it) and it occupies space (it takes room on the shelf).',
 visual:'matterSort',
 opts:[{en:'Because it occupies space and has mass.',ar:'لأنه يأخذ حيّزاً وله كتلة.'},
       {en:'Because it has pages and words.',ar:'لأن فيه صفحات وكلمات.'},
       {en:'Because it is a solid colour.',ar:'لأن لونه ثابت.'}],
 ans:0,
 whyAr:'هذا هو الجواب المعتمد: <b>الكتاب يأخذ حيّزاً وله كتلة</b>. الصفحات واللون خصائص، مو دليل على كونه مادة.',
 whyEn:'This is the expected answer: <b>a book occupies space and has mass</b>. Pages and colour are properties, not the test for matter.',
 trickAr:'اختبار المادة = كتلة ⚖️ + حيّز 📦',trickEn:'Matter test = mass ⚖️ + space 📦',
 chall:{qEn:'Is air matter?',qAr:'هل الهواء مادة؟',opts:[{en:'Yes — it has mass and takes up space',ar:'نعم — له كتلة ويأخذ حيّز'},{en:'No — we cannot see it',ar:'لا — ما نشوفه'}],ans:0}},

{id:'D-2',sec:'D',type:'mcq',concept:'L9',
 qEn:'A glass of water at 25°C and a large swimming pool at 25°C — which contains more thermal energy? Explain.',
 qAr:'كوب ماء ٢٥°م ومسبح كبير ٢٥°م — أيهما يحتوي طاقة حرارية أكبر؟ اشرح.',
 meanAr:'فخ! 🎯 نفس درجة الحرارة، فالسؤال يختبر: هل تعرف الفرق بين <b>المتوسط</b> و<b>المجموع</b>؟',
 ideaAr:'درجة الحرارة نفسها → متوسط الطاقة الحركية لكل جسيم نفسه. بس المسبح فيه جزيئات أكثر بكثير، لذلك <b>مجموع</b> الطاقة الحرارية فيه أكبر.',
 ideaEn:'Same temperature → the same average kinetic energy per particle. But the pool has far more particles, so its <b>total</b> thermal energy is much greater.',
 visual:'poolGlass',
 opts:[{en:'The swimming pool — larger samples of matter contain more total particles, giving them more overall thermal energy.',ar:'المسبح — الكميات الأكبر فيها جزيئات أكثر، فمجموع طاقتها الحرارية أكبر.'},
       {en:'The glass — smaller things heat up faster.',ar:'الكوب — الأشياء الصغيرة تسخن أسرع.'},
       {en:'Equal — the temperature is the same, so the energy is the same.',ar:'متساويان — نفس الحرارة يعني نفس الطاقة.'}],
 ans:0,
 whyAr:'لأن الطاقة الحرارية تعتمد على <b>كمية المادة</b> أيضاً، مو بس على درجة الحرارة. مليون جسيم دافئ مجموعهم أكبر من مئة جسيم دافئ.',
 whyEn:'Thermal energy depends on the <b>amount of matter</b> as well as the temperature. A million warm particles total more than a hundred warm particles.',
 wrong:{1:'سرعة التسخين شي ثاني، السؤال عن الطاقة المخزّنة الكلية.',2:'هذا الخطأ الشائع — الحرارة متوسط، الطاقة الحرارية مجموع.'},
 trickAr:'TEMPERATURE = متوسط 📉 · THERMAL = المجموع ➕',trickEn:'TEMPERATURE = average 📉 · THERMAL = total ➕',
 chall:{qEn:'Two identical cups, 25°C and 50°C. More thermal energy?',qAr:'كوبان متطابقان، ٢٥°م و٥٠°م. مين أكثر طاقة حرارية؟',
   opts:[{en:'The 50°C cup',ar:'كوب ٥٠°م'},{en:'The 25°C cup',ar:'كوب ٢٥°م'}],ans:0}},

{id:'D-3',sec:'D',type:'build',concept:'L15',build:'H2O2',
 qEn:'A molecule of hydrogen peroxide is made of two hydrogen (H) atoms and two oxygen (O) atoms bonded together. Write its correct chemical formula.',
 qAr:'جزيء فوق أكسيد الهيدروجين مكوّن من ذرتي هيدروجين (H) وذرتي أكسجين (O) مرتبطتين. اكتب صيغته الكيميائية.',
 meanAr:'السؤال يبيك <b>تحوّل الكلام إلى صيغة</b>: عدّ الذرات واكتبها كرمز + رقم صغير.',
 ideaAr:'٢ هيدروجين → H₂ · ٢ أكسجين → O₂ · نكتبهم ورا بعض: H₂O₂.',
 ideaEn:'2 hydrogen → H₂ · 2 oxygen → O₂ · write them together: H₂O₂.',
 answerEn:'H₂O₂',answerAr:'H₂O₂',
 whyAr:'كل عدد ذرات يصير رقماً صغيراً بعد رمز عنصره. انتبه: H₂O₂ غير H₂O — النسبة مختلفة فالمادة مختلفة تماماً!',
 whyEn:'Each atom count becomes a subscript after its symbol. Careful: H₂O₂ is not H₂O — a different ratio means a completely different substance!',
 trickAr:'ماء + أكسجين زيادة = ماء أكسجيني H₂O₂ 🧴',trickEn:'Water with an extra O = hydrogen peroxide H₂O₂ 🧴',
 chall:{qEn:'How many atoms in total are in H₂O₂?',qAr:'كم مجموع الذرات في H₂O₂؟',
   opts:[{en:'4',ar:'٤'},{en:'2',ar:'٢'},{en:'3',ar:'٣'}],ans:0}},

{id:'D-4',sec:'D',type:'count',concept:'L15',
 qEn:'Baking soda is NaHCO₃. Identify how many different elements are present, and the total number of atoms in one molecule.',
 qAr:'بيكربونات الصوديوم NaHCO₃. كم عنصراً مختلفاً فيها؟ وكم مجموع الذرات في جزيء واحد؟',
 meanAr:'سؤالين في واحد: (١) عدد <b>أنواع</b> العناصر، (٢) عدد <b>الذرات</b> الكلي.',
 ideaAr:'العناصر: Na صوديوم، H هيدروجين، C كربون، O أكسجين = <b>٤ عناصر</b>.<br>الذرات: Na=١، H=١، C=١، O=٣ (الرقم الصغير ٣) → المجموع <b>٦ ذرات</b>.',
 ideaEn:'Elements: Na sodium, H hydrogen, C carbon, O oxygen = <b>4 elements</b>.<br>Atoms: Na=1, H=1, C=1, O=3 (subscript 3) → total <b>6 atoms</b>.',
 visual:'nahco3',
 opts:[{en:'4 different elements · 6 atoms in total',ar:'٤ عناصر مختلفة · ٦ ذرات إجمالاً'},
       {en:'3 different elements · 5 atoms in total',ar:'٣ عناصر مختلفة · ٥ ذرات إجمالاً'},
       {en:'4 different elements · 4 atoms in total',ar:'٤ عناصر مختلفة · ٤ ذرات إجمالاً'}],
 ans:0,
 whyAr:'1 Na + 1 H + 1 C + 3 O = 6 ذرات. والعناصر أربعة لأننا نعد <b>الأنواع</b> مو الذرات.',
 whyEn:'1 Na + 1 H + 1 C + 3 O = 6 atoms. There are four elements because we count <b>types</b>, not atoms.',
 trickAr:'إذا ما فيه رقم صغير → احسبه ١ ☝️',trickEn:'No little number → count ONE ☝️',
 chall:{qEn:'In NaHCO₃, how many oxygen atoms?',qAr:'في NaHCO₃ كم ذرة أكسجين؟',opts:[{en:'3',ar:'٣'},{en:'1',ar:'١'}],ans:0}},

{id:'D-5',sec:'D',type:'mcq',concept:'L0',
 qEn:'We heated a beaker of liquid water until it boiled into water vapour. What visible evidence showed that a gas was forming?',
 qAr:'سخّنا كأس ماء حتى غلى وتحول لبخار. وش الدليل المرئي اللي يثبت أن غازاً يتكوّن؟',
 meanAr:'السؤال يبي <b>ملاحظة بالعين</b>، مو تفسير نظري.',
 ideaAr:'وقت الغليان: تتكوّن <b>فقاعات كبيرة داخل السائل</b> تطلع للسطح، ويطلع <b>بخار/دخان أبيض</b> من فوق الكأس. الفقاعة نفسها = جيب غاز.',
 ideaEn:'During boiling you see <b>large bubbles forming through the liquid</b> and rising, and <b>steam/vapour rising</b> out of the beaker. A bubble is a pocket of gas.',
 visual:'boil',
 opts:[{en:'Large bubbles forming throughout the liquid and rising to the top, and steam/vapour rising out of the beaker.',ar:'فقاعات كبيرة تتكوّن داخل السائل وترتفع للأعلى، وبخار يتصاعد من الكأس.'},
       {en:'The water changed colour.',ar:'الماء تغيّر لونه.'},
       {en:'The beaker became heavier.',ar:'الكأس صار أثقل.'}],
 ans:0,
 whyAr:'لأن الفقاعات هي ماء تحوّل لحالة الغاز داخل السائل نفسه، والبخار هو الغاز وهو يهرب للهواء.',
 whyEn:'The bubbles are water that turned into gas inside the liquid, and the steam is that gas escaping into the air.',
 wrong:{1:'الماء ما يتغير لونه بالغليان.',2:'بالعكس، الكأس يخف لأن جزء من الماء يطير كبخار.'},
 trickAr:'فقاعات + بخار = غاز يتكوّن 🫧♨️',trickEn:'Bubbles + steam = gas forming 🫧♨️',
 chall:{qEn:'A bubble inside boiling water contains…',qAr:'الفقاعة داخل الماء المغلي فيها…',
   opts:[{en:'Water in the gas state',ar:'ماء في الحالة الغازية'},{en:'Empty nothing',ar:'فراغ تماماً'}],ans:0}},

/* ============ E. WORD BANK ============ */
{id:'E-1',sec:'E',type:'fill',concept:'L3',
 qEn:'In ______, the particles are packed tightly together.',qAr:'في ______ تكون الجزيئات متراصة بإحكام.',
 meanAr:'أي حالة جزيئاتها ألصق ببعض؟',
 ideaAr:'أقرب ترتيب وأقوى تجاذب = المواد الصلبة.',ideaEn:'The closest packing and strongest attraction = solids.',
 answer:'Solids',answerAr:'المواد الصلبة (Solids)',
 whyAr:'لأن الصلب جزيئاته في تركيب ثابت متراص.',whyEn:'Because a solid has a rigid, tightly packed structure.',
 trickAr:'صلب = متراص 🧊',trickEn:'Solid = packed 🧊',
 chall:{qEn:'Tightly packed + vibrating =',qAr:'متراص + يهتز =',opts:[{en:'Solid',ar:'صلب'},{en:'Gas',ar:'غاز'}],ans:0}},

{id:'E-2',sec:'E',type:'fill',concept:'L3',
 qEn:'Solid particles ______ in place.',qAr:'جزيئات الصلب ______ في مكانها.',
 meanAr:'وش نوع الحركة الوحيدة المسموحة للصلب؟',
 ideaAr:'ما تنتقل ولا تنزلق، بس تهتز ذهاباً وإياباً في مكانها.',ideaEn:'They do not travel or slide; they only vibrate back and forth in place.',
 answer:'Vibrate',answerAr:'تهتز (Vibrate)',
 whyAr:'لأن التجاذب القوي يمسكها في مواضعها فما تقدر تتحرك إلا اهتزازاً.',whyEn:'Strong attraction holds them in position, so vibration is all they can do.',
 trickAr:'الصلب يرقص بمكانه 🕺 ما يمشي.',trickEn:'A solid dances in place 🕺 it does not walk.',
 chall:{qEn:'Do liquid particles vibrate in fixed positions?',qAr:'هل جزيئات السائل تهتز في مواضع ثابتة؟',opts:[{en:'No, they slide',ar:'لا، تنزلق'},{en:'Yes',ar:'نعم'}],ans:0}},

{id:'E-3',sec:'E',type:'fill',concept:'L7',
 qEn:'Particles close together exert ______ forces.',qAr:'الجزيئات القريبة من بعضها تبذل قوى ______.',
 meanAr:'وش نوع القوة اللي تشد الجزيئات لبعض؟',
 ideaAr:'قوى تجاذب — تسحب الجزيئات نحو بعض مثل المغناطيس.',ideaEn:'Attractive forces — they pull particles toward each other like magnets.',
 answer:'Attractive',answerAr:'تجاذب (Attractive)',
 whyAr:'القرب يخلق التجاذب، والتجاذب يحدد حالة المادة.',whyEn:'Closeness creates attraction, and attraction helps decide the state of matter.',
 trickAr:'قريب = يشد 🧲',trickEn:'Close = pull 🧲',
 chall:{qEn:'Which state has the strongest attractive forces?',qAr:'أي حالة فيها أقوى قوى تجاذب؟',opts:[{en:'Solids',ar:'الصلبة'},{en:'Gases',ar:'الغازات'}],ans:0}},

{id:'E-4',sec:'E',type:'fill',concept:'L3',
 qEn:'In ______, the particles are widely spaced apart and zoom around at very high speeds.',qAr:'في ______ تكون الجزيئات متباعدة وتنطلق بسرعات عالية جداً.',
 meanAr:'مين الحالة الأكثر فوضى وسرعة؟',
 ideaAr:'الغازات — مسافات كبيرة وسرعة عالية وحركة عشوائية.',ideaEn:'Gases — big spaces, high speed, random motion.',
 answer:'Gases',answerAr:'الغازات (Gases)',
 whyAr:'لأن تجاذبها ضعيف فما فيه شي يمسكها.',whyEn:'Their attraction is weak, so nothing holds them back.',
 trickAr:'الغاز = صاروخ 🚀',trickEn:'Gas = rocket 🚀',
 chall:{qEn:'Widely spaced + very fast =',qAr:'متباعد + سريع جداً =',opts:[{en:'Gas',ar:'غاز'},{en:'Liquid',ar:'سائل'}],ans:0}},

{id:'E-5',sec:'E',type:'fill',concept:'L8',
 qEn:'Because gas particles have so much empty space between them, they possess the highest amount of ______ energy.',
 qAr:'لأن جزيئات الغاز بينها فراغ كبير، فهي تمتلك أعلى قدر من طاقة ______.',
 meanAr:'الفراغ والمسافة يرتبطان بأي نوع طاقة؟',
 ideaAr:'المسافة = طاقة وضع مخزّنة. الغاز الأبعد → أعلى طاقة وضع.',ideaEn:'Distance = stored potential energy. Gas is farthest apart → highest potential energy.',
 answer:'Potential',answerAr:'الوضع (Potential)',
 whyAr:'ما نقول حركية لأن السؤال يتكلم عن <b>الفراغ</b> مو السرعة.',whyEn:'Not kinetic, because the sentence is about <b>space</b>, not speed.',
 trickAr:'فراغ = Potential 🔋',trickEn:'Space = Potential 🔋',
 chall:{qEn:'Potential energy depends on…',qAr:'طاقة الوضع تعتمد على…',opts:[{en:'Distance between particles',ar:'المسافة بين الجزيئات'},{en:'Particle colour',ar:'لون الجسيمات'}],ans:0}},

{id:'E-6',sec:'E',type:'fill',concept:'L9',
 qEn:'When you heat up a substance, you are adding ______ energy to it.',qAr:'لما تسخّن مادة فأنت تضيف لها طاقة ______.',
 meanAr:'التسخين يضيف أي نوع طاقة للمادة كلها؟',
 ideaAr:'التسخين يضيف طاقة حرارية، وهي تزيد حركة الجزيئات وتقدر تغيّر حالة المادة.',ideaEn:'Heating adds thermal energy, which increases particle motion and can change the state of matter.',
 answer:'Thermal',answerAr:'حرارية (Thermal)',
 whyAr:'الطاقة الحرارية هي الطاقة الكلية المنتقلة للمادة عند التسخين.',whyEn:'Thermal energy is the total energy transferred into the substance when it is heated.',
 trickAr:'تسخين = إضافة Thermal ♨️',trickEn:'Heating = adding Thermal ♨️',
 chall:{qEn:'Removing thermal energy makes particles…',qAr:'سحب الطاقة الحرارية يجعل الجزيئات…',opts:[{en:'Slower',ar:'أبطأ'},{en:'Faster',ar:'أسرع'}],ans:0}},

{id:'E-7',sec:'E',type:'fill',concept:'L6',
 qEn:'We can measure temperature using a ______.',qAr:'نقدر نقيس درجة الحرارة باستخدام ______.',
 meanAr:'وش اسم الأداة؟',
 ideaAr:'الترمومتر (مقياس الحرارة) — يقيس متوسط الطاقة الحركية للجزيئات.',ideaEn:'A thermometer — it measures the average kinetic energy of the particles.',
 answer:'Thermometer',answerAr:'ترمومتر (Thermometer)',
 whyAr:'الأداة اسمها ترمومتر، والمقاييس المستخدمة سيليزيوس وفهرنهايت وكلفن.',whyEn:'The tool is a thermometer; the scales are Celsius, Fahrenheit and Kelvin.',
 trickAr:'Thermo = حرارة · meter = مقياس 🌡️',trickEn:'Thermo = heat · meter = measure 🌡️',
 chall:{qEn:'Which is NOT a temperature scale?',qAr:'أي وحدة ليست مقياس حرارة؟',opts:[{en:'Newton',ar:'نيوتن'},{en:'Kelvin',ar:'كلفن'}],ans:0}},

{id:'E-8',sec:'E',type:'fill',concept:'L5',
 qEn:'Temperature measures the average ______ energy of particles in a material.',qAr:'درجة الحرارة تقيس متوسط طاقة ______ لجزيئات المادة.',
 meanAr:'درجة الحرارة متوسط أي طاقة بالضبط؟',
 ideaAr:'متوسط الطاقة <b>الحركية</b> — يعني متوسط سرعة حركة الجزيئات.',ideaEn:'The average <b>kinetic</b> energy — the average energy of particle motion.',
 answer:'Kinetic',answerAr:'حركية (Kinetic)',
 whyAr:'الحرارة ما تقيس المجموع (ذاك Thermal)، تقيس المتوسط الحركي.',whyEn:'Temperature does not measure the total (that is thermal); it measures the average kinetic energy.',
 trickAr:'Temperature = متوسط Kinetic 📉',trickEn:'Temperature = average Kinetic 📉',
 chall:{qEn:'Thermal energy is the ______ energy.',qAr:'الطاقة الحرارية هي الطاقة ______.',opts:[{en:'Total',ar:'الكلية'},{en:'Average',ar:'المتوسطة'}],ans:0}},

{id:'E-9',sec:'E',type:'fill',concept:'L5',
 qEn:'At higher ______, particles move faster because they have more kinetic energy.',qAr:'عند ______ أعلى تتحرك الجزيئات أسرع لأن طاقتها الحركية أكبر.',
 meanAr:'وش الشي اللي إذا ارتفع صارت الجزيئات أسرع؟',
 ideaAr:'درجة الحرارة. ارتفاعها = جزيئات أسرع = طاقة حركية أكبر.',ideaEn:'Temperature. Higher temperature = faster particles = more kinetic energy.',
 answer:'Temperature',answerAr:'درجة حرارة (Temperature)',
 whyAr:'العلاقة طردية: حرارة ↑ = حركة ↑ = طاقة حركية ↑.',whyEn:'Direct relationship: temperature ↑ = motion ↑ = kinetic energy ↑.',
 trickAr:'🌡️↑ = 🏃↑',trickEn:'🌡️↑ = 🏃↑',
 chall:{qEn:'At 0 K particles…',qAr:'عند ٠ كلفن الجزيئات…',opts:[{en:'Stop all motion',ar:'تتوقف تماماً'},{en:'Move fastest',ar:'تتحرك بأقصى سرعة'}],ans:0}},

/* ============ F. COMPOUND MODELS ============ */
{id:'F-1',sec:'F',type:'model',concept:'L15',
 model:{center:'N',around:['H','H','H'],formula:'NH3',display:'NH₃'},
 qEn:'Write the chemical formula for this compound model (Key: large light-blue = N, small blue = H, red = O).',
 qAr:'اكتب الصيغة الكيميائية لهذا النموذج (المفتاح: الأزرق الفاتح الكبير = N، الأزرق الصغير = H، الأحمر = O).',
 meanAr:'السؤال يبيك: (١) تشوف المفتاح، (٢) تحدد نوع كل كرة، (٣) تعدّها، (٤) تكتب الصيغة.',
 ideaAr:'في النموذج: كرة كبيرة فاتحة في النص = نيتروجين N (واحدة)، وثلاث كرات صغيرة = هيدروجين H. إذن N₁H₃ ونحذف الـ ١ → <b>NH₃</b>.',
 ideaEn:'In the model: one big light-blue sphere = nitrogen N (one), and three small spheres = hydrogen H. So N₁H₃, and we drop the 1 → <b>NH₃</b>.',
 opts:[{en:'NH₃',ar:'NH₃'},{en:'N₃H',ar:'N₃H'},{en:'NH₄',ar:'NH₄'},{en:'H₃O',ar:'H₃O'}],
 ans:0,
 whyAr:'ذرة نيتروجين واحدة (ما نكتب ١) + ٣ هيدروجين (نكتب ٣ صغيرة تحت H) = NH₃. هذا غاز الأمونيا.',
 whyEn:'One nitrogen atom (we never write 1) + 3 hydrogens (subscript 3 under H) = NH₃. This is ammonia.',
 wrong:{1:'N₃H يعني ٣ نيتروجين وهيدروجين واحد — معكوس.',2:'NH₄ يعني ٤ هيدروجين، وإحنا عددنا ٣ بس.',3:'ما فيه أكسجين (أحمر) في هذا النموذج.'},
 trickAr:'عدّ الكرات الصغيرة الملتصقة بالكبيرة ⚪⚪⚪',trickEn:'Count the small spheres attached to the big one ⚪⚪⚪',
 chall:{qEn:'How many atoms in total in NH₃?',qAr:'كم مجموع الذرات في NH₃؟',opts:[{en:'4',ar:'٤'},{en:'3',ar:'٣'}],ans:0}},

{id:'F-2',sec:'F',type:'model',concept:'L15',
 model:{chain:['H','O','O','H'],formula:'H2O2',display:'H₂O₂'},
 qEn:'Write the chemical formula for this compound model (two red spheres bonded together, each with one small blue sphere).',
 qAr:'اكتب الصيغة الكيميائية لهذا النموذج (كرتان حمراوان مرتبطتان، وكل وحدة معها كرة زرقاء صغيرة).',
 meanAr:'عدّ الأحمر (أكسجين) والأزرق الصغير (هيدروجين)، ثم اكتب الصيغة.',
 ideaAr:'أحمر × ٢ = أكسجين ٢ · أزرق صغير × ٢ = هيدروجين ٢ → نكتب الهيدروجين أولاً: <b>H₂O₂</b>.',
 ideaEn:'Red × 2 = 2 oxygen · small blue × 2 = 2 hydrogen → hydrogen first: <b>H₂O₂</b>.',
 opts:[{en:'H₂O₂',ar:'H₂O₂'},{en:'H₂O',ar:'H₂O'},{en:'HO',ar:'HO'},{en:'O₂H',ar:'O₂H'}],
 ans:0,
 whyAr:'ذرتا أكسجين مرتبطتان ببعض وكل وحدة معها هيدروجين → H₂O₂ (فوق أكسيد الهيدروجين). لو كان أكسجين واحد بس صارت H₂O.',
 whyEn:'Two oxygens bonded to each other, each carrying one hydrogen → H₂O₂ (hydrogen peroxide). With only one oxygen it would be H₂O.',
 wrong:{1:'H₂O فيها أكسجين واحد، وإحنا نشوف اثنين.',2:'HO يعني ذرة من كل نوع، والعدد هنا اثنان لكل نوع.',3:'الترتيب المعتاد يبدأ بالهيدروجين، والأعداد صحيحة لكن الصيغة تُكتب H₂O₂.'},
 trickAr:'كرتين حمر = O₂ 🔴🔴',trickEn:'Two reds = O₂ 🔴🔴',
 chall:{qEn:'H₂O₂ and H₂O are…',qAr:'H₂O₂ و H₂O هما…',opts:[{en:'Different compounds',ar:'مركبان مختلفان'},{en:'The same substance',ar:'نفس المادة'}],ans:0}},

{id:'F-3',sec:'F',type:'model',concept:'L15',
 model:{center:'N',around:['O','O','H'],formula:'HNO2',display:'HNO₂',note:'H bonded to one O'},
 qEn:'Write the chemical formula for this compound model (one large light-blue N, two red O, one small blue H attached to an O).',
 qAr:'اكتب الصيغة الكيميائية لهذا النموذج (نيتروجين N كبير فاتح، وأكسجينان أحمران، وهيدروجين صغير مرتبط بأحد الأكسجينين).',
 meanAr:'نفس الخطوات: اقرأ المفتاح، صنّف كل كرة، عدّها، ثم اكتب الصيغة.',
 ideaAr:'نيتروجين ١ + أكسجين ٢ + هيدروجين ١ → نكتب الهيدروجين أولاً ثم النيتروجين ثم الأكسجين: <b>HNO₂</b>.',
 ideaEn:'1 nitrogen + 2 oxygen + 1 hydrogen → hydrogen first, then nitrogen, then oxygen: <b>HNO₂</b>.',
 opts:[{en:'HNO₂',ar:'HNO₂'},{en:'HNO₃',ar:'HNO₃'},{en:'NO₂',ar:'NO₂'},{en:'H₂NO',ar:'H₂NO'}],
 ans:0,
 whyAr:'عندنا ٤ ذرات: H واحدة، N واحدة، O اثنتان → HNO₂. ما نكتب ١ للهيدروجين ولا للنيتروجين.',
 whyEn:'Four atoms: one H, one N, two O → HNO₂. We never write the 1 for H or N.',
 wrong:{1:'HNO₃ فيها ٣ أكسجين، والنموذج فيه أحمرين بس.',2:'NO₂ ناقصها الهيدروجين الأزرق الصغير.',3:'H₂NO تعني هيدروجينين وأكسجين واحد — عكس ما نشوف.'},
 trickAr:'عدّ الأحمر = عدد O 🔴، والصغير الأزرق = H 🔵',trickEn:'Count reds = O 🔴, small blues = H 🔵',
 chall:{qEn:'How many different elements are in HNO₂?',qAr:'كم عنصراً مختلفاً في HNO₂؟',opts:[{en:'3',ar:'٣'},{en:'2',ar:'٢'},{en:'4',ar:'٤'}],ans:0}},

/* ============ G. TRUE / FALSE ============ */
{id:'G-1',sec:'G',type:'tf',concept:'L8',
 qEn:'A particle can have potential and kinetic energy.',qAr:'الجسيم ممكن يملك طاقة وضع وطاقة حركية في نفس الوقت.',
 meanAr:'هل النوعان يجتمعان في نفس الجسيم؟',
 ideaAr:'أكيد! الجسيم يتحرك (حركية) وفي نفس اللحظة بينه وبين جيرانه مسافة وتجاذب (وضع). ومجموعهما = الطاقة الحرارية.',
 ideaEn:'Yes! A particle moves (kinetic) and at the same moment has distance and attraction with its neighbours (potential). Their sum = thermal energy.',
 ans:true,
 whyAr:'الطاقة الحرارية نفسها معرّفة على أنها حركية + وضع، فلازم يجتمعون.',whyEn:'Thermal energy is defined as kinetic + potential, so both exist together.',
 trickAr:'حركة + مسافة = الاثنين مع بعض ✌️',trickEn:'Motion + spacing = both at once ✌️',
 chall:{qEn:'Thermal energy = kinetic + ______',qAr:'الطاقة الحرارية = حركية + ______',opts:[{en:'Potential',ar:'وضع'},{en:'Light',ar:'ضوء'}],ans:0}},

{id:'G-2',sec:'G',type:'tf',concept:'L5',
 qEn:'Kinetic energy measures the temperature.',qAr:'الطاقة الحركية تقيس درجة الحرارة.',
 meanAr:'انتبه للاتجاه! مين يقيس مين؟',
 ideaAr:'العكس هو الصحيح: <b>درجة الحرارة تقيس متوسط الطاقة الحركية</b>، مو الطاقة الحركية تقيس الحرارة.',
 ideaEn:'It is the other way round: <b>temperature measures the average kinetic energy</b>, not the reverse.',
 ans:false,
 whyAr:'الجملة مقلوبة. الترمومتر يقيس الحرارة، والحرارة تعبّر عن متوسط الطاقة الحركية.',whyEn:'The sentence is reversed. A thermometer measures temperature, and temperature expresses average kinetic energy.',
 trickAr:'الحرارة 🌡️ هي المقياس، والحركة هي المقيس.',trickEn:'Temperature 🌡️ is the measurer; motion is what is measured.',
 chall:{qEn:'Temperature measures the ______ kinetic energy.',qAr:'درجة الحرارة تقيس ______ الطاقة الحركية.',opts:[{en:'Average',ar:'متوسط'},{en:'Total',ar:'مجموع'}],ans:0}},

{id:'G-3',sec:'G',type:'tf',concept:'L2',
 qEn:'Gases have definite shape.',qAr:'الغازات لها شكل ثابت.',
 meanAr:'هل الغاز يحافظ على شكله؟',
 ideaAr:'لا! الغاز ما له شكل ثابت ولا حجم ثابت — ينتشر ويملأ الإناء كله.',
 ideaEn:'No! A gas has no definite shape and no definite volume — it spreads out and fills the whole container.',
 ans:false,
 whyAr:'الشكل الثابت للصلب فقط. السائل يأخذ شكل الإناء، والغاز يملأه كله.',whyEn:'Only solids have a definite shape. A liquid takes the container shape and a gas fills it completely.',
 trickAr:'عطر في الغرفة ينتشر كله = ما له شكل 💨',trickEn:'Perfume spreads through the room = no shape 💨',
 chall:{qEn:'Which has BOTH definite shape and volume?',qAr:'أي حالة لها شكل وحجم ثابتان معاً؟',opts:[{en:'Solid',ar:'الصلب'},{en:'Gas',ar:'الغاز'}],ans:0}},

{id:'G-4',sec:'G',type:'tf',concept:'L6',
 qEn:'Temperature scales include Celsius, Fahrenheit, and Kelvin.',qAr:'مقاييس الحرارة تشمل سيليزيوس وفهرنهايت وكلفن.',
 meanAr:'هل هذي فعلاً أسماء مقاييس الحرارة؟',
 ideaAr:'نعم، الثلاثة مقاييس حرارة. العلماء حول العالم يستخدمون سيليزيوس، وكلفن يبدأ من الصفر المطلق.',
 ideaEn:'Yes, all three are temperature scales. Scientists worldwide use Celsius, and Kelvin starts at absolute zero.',
 ans:true,
 whyAr:'هي المقاييس الثلاثة المذكورة في الدرس بالضبط.',whyEn:'These are exactly the three scales named in the lesson.',
 trickAr:'C · F · K = ثلاثة مقاييس 🌡️',trickEn:'C · F · K = three scales 🌡️',
 chall:{qEn:'Which scale starts at absolute zero?',qAr:'أي مقياس يبدأ من الصفر المطلق؟',opts:[{en:'Kelvin',ar:'كلفن'},{en:'Celsius',ar:'سيليزيوس'}],ans:0}},

{id:'G-5',sec:'G',type:'tf',concept:'L3',
 qEn:'In liquids, particles vibrate (in fixed positions).',qAr:'في السوائل تهتز الجزيئات (في مواضع ثابتة).',
 meanAr:'الاهتزاز في المكان صفة أي حالة؟',
 ideaAr:'الاهتزاز في مواضع ثابتة صفة <b>الصلب</b>. جزيئات السائل تتحرك عشوائياً وتنزلق جنب بعض.',
 ideaEn:'Vibrating in fixed positions describes a <b>solid</b>. Liquid particles move randomly and slide past one another.',
 ans:false,
 whyAr:'لو كانت جزيئات السائل تهتز في مكانها، كان السائل حافظ على شكله — وهذا ما يصير.',whyEn:'If liquid particles vibrated in place, a liquid would keep its shape — but it does not.',
 trickAr:'صلب يهتز 🧊 · سائل ينزلق 💧',trickEn:'Solid vibrates 🧊 · Liquid slides 💧',
 chall:{qEn:'Sliding past one another describes…',qAr:'الانزلاق جنب بعض يصف…',opts:[{en:'Liquid',ar:'السائل'},{en:'Solid',ar:'الصلب'}],ans:0}},

{id:'G-6',sec:'G',type:'tf',concept:'L6',
 qEn:'The temperature at which particles stop all motion and have no kinetic energy is called absolute zero.',
 qAr:'درجة الحرارة التي تتوقف عندها حركة الجزيئات تماماً ولا تملك طاقة حركية تسمى الصفر المطلق.',
 meanAr:'هل هذا هو تعريف الصفر المطلق؟',
 ideaAr:'نعم — الصفر المطلق = 0 كلفن، وعنده تتوقف كل حركة وما فيه طاقة حركية.',
 ideaEn:'Yes — absolute zero = 0 K, where all motion stops and there is no kinetic energy.',
 ans:true,
 whyAr:'ومقياس كلفن يبدأ من هذي النقطة بالضبط.',whyEn:'The Kelvin scale starts exactly at that point.',
 trickAr:'0 K = سكون تام 🧊🛑',trickEn:'0 K = total stillness 🧊🛑',
 chall:{qEn:'Absolute zero equals…',qAr:'الصفر المطلق يساوي…',opts:[{en:'0 K',ar:'٠ كلفن'},{en:'0 °C',ar:'٠ °م'}],ans:0}},

/* ============ H. DRAW THE ARRANGEMENT ============ */
{id:'H-1',sec:'H',type:'draw',state:'gas',concept:'L3',
 qEn:'Draw the arrangement of particles in a GAS.',qAr:'ارسم ترتيب الجزيئات في الغاز.',
 meanAr:'السؤال يبيك ترسم/تحط الجزيئات بالترتيب الصحيح داخل المربع.',
 ideaAr:'الغاز: جزيئات <b>قليلة ومتباعدة جداً</b>، موزعة عشوائياً في كل المربع.',
 ideaEn:'Gas: <b>few particles, very far apart</b>, spread randomly all over the box.',
 whyAr:'لأن تجاذب الغاز ضعيف وحركته سريعة، فالجزيئات تنتشر وتملأ الإناء.',whyEn:'Gas attraction is weak and motion is fast, so the particles spread out and fill the container.',
 trickAr:'غاز = فراغ كثير بين الكرات ⚪   ⚪   ⚪',trickEn:'Gas = lots of empty space ⚪   ⚪   ⚪',
 chall:{qEn:'Gas particles fill…',qAr:'جزيئات الغاز تملأ…',opts:[{en:'The whole container',ar:'الإناء كله'},{en:'The bottom only',ar:'القاع فقط'}],ans:0}},

{id:'H-2',sec:'H',type:'draw',state:'solid',concept:'L3',
 qEn:'Draw the arrangement of particles in a SOLID.',qAr:'ارسم ترتيب الجزيئات في الصلب.',
 meanAr:'ارسم الترتيب الصحيح للجزيئات في الحالة الصلبة.',
 ideaAr:'الصلب: جزيئات <b>كثيرة، متلاصقة، ومرتّبة في صفوف منتظمة</b> (شبكة).',
 ideaEn:'Solid: <b>many particles, touching, in neat regular rows</b> (a lattice).',
 whyAr:'لأن التجاذب قوي جداً فيمسكها في تركيب ثابت، وما تقدر إلا تهتز في مكانها.',whyEn:'Attraction is very strong, holding them in a rigid structure where they can only vibrate in place.',
 trickAr:'صلب = صفوف مثل طابور المدرسة 🧊',trickEn:'Solid = neat rows like a school line 🧊',
 chall:{qEn:'Solid particles are arranged…',qAr:'جزيئات الصلب مرتبة…',opts:[{en:'Closely and regularly',ar:'متقاربة ومنتظمة'},{en:'Far apart',ar:'متباعدة'}],ans:0}},

{id:'H-3',sec:'H',type:'draw',state:'liquid',concept:'L3',
 qEn:'Draw the arrangement of particles in a LIQUID.',qAr:'ارسم ترتيب الجزيئات في السائل.',
 meanAr:'ارسم الترتيب الصحيح للجزيئات في الحالة السائلة.',
 ideaAr:'السائل: جزيئات <b>قريبة من بعض لكن غير مرتّبة</b>، تتجمع في الأسفل وتقدر تنزلق.',
 ideaEn:'Liquid: <b>close together but not in order</b>, gathered at the bottom and able to slide.',
 whyAr:'قربها يعطي حجماً ثابتاً، وعدم انتظامها يعطيها القدرة على الجريان وأخذ شكل الإناء.',whyEn:'Being close gives a definite volume; being disordered lets it flow and take the container shape.',
 trickAr:'سائل = قريب بس فوضوي 💧',trickEn:'Liquid = close but messy 💧',
 chall:{qEn:'Compared to a solid, liquid particles are…',qAr:'مقارنة بالصلب، جزيئات السائل…',opts:[{en:'Close but disordered',ar:'قريبة لكن غير منتظمة'},{en:'Perfectly ordered',ar:'منتظمة تماماً'}],ans:0}}
];

/* ---------- BADGES ---------- */
const BADGES = [
 {id:'particle',ic:'🧊',en:'Particle Pro',ar:'خبير الجزيئات',need:q=>q.filter(x=>['A-1','A-5','H-1','H-2','H-3'].includes(x)).length>=4},
 {id:'matter',ic:'🌍',en:'Matter Master',ar:'سيد المادة',need:q=>q.filter(x=>x.startsWith('B-')||x==='D-1').length>=3},
 {id:'mol',ic:'⚛️',en:'Molecule Builder',ar:'بنّاء الجزيئات',need:q=>q.filter(x=>x.startsWith('F-')||['D-3','D-4','A-4'].includes(x)).length>=4},
 {id:'energy',ic:'⚡',en:'Energy Expert',ar:'عبقري الطاقة',need:q=>q.filter(x=>['A-2','A-3','A-8','C-1','C-2','C-3','D-2'].includes(x)).length>=5},
 {id:'all',ic:'🏆',en:'Question Bank Champion',ar:'بطل بنك الأسئلة',need:q=>q.length>=QB.length}
];

const WORDBANK=['Kinetic','Potential','Thermal','Temperature','Solids','Gases','Vibrate','Attractive','Thermometer'];
